DROP TABLE IF EXISTS TBL_PHONE;
DROP TABLE IF EXISTS TBL_USER;

CREATE TABLE TBL_USER (
    id VARCHAR(250) PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(250) DEFAULT NULL,
    password VARCHAR(250) NOT NULL,
    token VARCHAR(250) NOT NULL,
    active BOOLEAN NOT NULL,
    created DATE NOT NULL,
    modified DATE,
    lastlogin DATE NOT NULL
);

CREATE TABLE TBL_PHONE (
    id INTEGER PRIMARY KEY,
    user_id VARCHAR(250),
    number VARCHAR(250),
    citycode VARCHAR(250),
    contrycode VARCHAR(250)
);

ALTER TABLE TBL_PHONE ADD CONSTRAINT FK_TBL_PHONE_USER_ID FOREIGN KEY (USER_ID) REFERENCES TBL_USER (ID);